# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            EditWall
tagline:          'Random Yesterdays for Tomorrow'
description:      'Hello, World!'
url:              http://mors.github.io

author:
  name:           'Aamo'
  url:            https://twitter.com/mooors

paginate:         5
